title: Wellness Multiomics Knowledge Base
description: Educational resources on stats, biomarkers, and recommendations for multiomics analysis.
theme: minima  # Simple default theme; change to another like 'jekyll-theme-cayman' if preferred.
plugins:
  - jekyll-feed  # Optional: For RSS if needed.
collections:
  stats:
    output: true  # Generates permalinks for each item.
  biomarkers:
    output: true
  recommendations:
    output: true
defaults:
  - scope:
      path: ""
    values:
      layout: default  # Applies to all pages.
